const $=id=>document.getElementById(id);
const state={rows:[],selected:null,sort:'ev',detail:null,minutes:30,pending:null,chart:[],request:0};
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(v,d=2)=>v==null?'--':Math.abs(v)>99999?Number(v).toExponential(2):Number(v).toFixed(d);
const money=v=>v==null?'--':(v<0?'-$':'$')+Math.abs(v).toFixed(2);
const pct=v=>v==null?'--':(v>0&&v<.00005?(v*100).toExponential(2):n(v*100))+'%';
const time=v=>v?new Date(v).toISOString().replace('T',' ').slice(0,19)+' UTC':'--';
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||r.statusText);return d;}
function activeRows(){const f=$('filter').value.toLowerCase();return state.rows.filter(r=>(r.asset+' '+r.event_text).toLowerCase().includes(f)).sort((a,b)=>{const v=r=>state.sort==='gap'?(r.math.gap_pp==null?-Infinity:Math.abs(r.math.gap_pp)):state.sort==='pm'?r.pm_yes:state.sort==='opt'?r.opt_yes:state.sort==='roi'?r.trade?.roi:state.sort==='n'?r.history?.n_blocks:r.trade&&['EXECUTABLE_SNAPSHOT','PROXY_EXECUTABLE'].includes(r.execution_state)?r.trade.ev:-Infinity;return (v(b)??-Infinity)-(v(a)??-Infinity)||Math.abs(b.math.gap_pp||0)-Math.abs(a.math.gap_pp||0);});}
function table(){const rows=activeRows();$('count').textContent=rows.length+' markets';$('market-body').innerHTML=rows.length?rows.map(r=>`<tr data-event="${escape(r.event_id)}" tabindex="0" class="${state.selected===r.event_id?'selected':''}"><td>${escape(r.asset)}</td><td title="${escape(r.event_text)}">${escape(r.event_type)} ${n(r.strike_or_threshold,0)} ${r.direction==='up'?'↑':'↓'}</td><td>${time(r.expiry).slice(5,16)}</td><td>${pct(r.pm_yes)}</td><td>${pct(r.opt_yes)}</td><td>${n(r.math.gap_pp)}</td><td>${n(r.math.odds_ratio)}×</td><td title="${escape(r.trade_reason)}">${r.trade?escape(r.trade.kind.replaceAll('_',' '))+(r.execution_state==='MARKET_CLOSED'?' [CLOSED]':''):'NONE'}</td><td>${money(r.trade?.debit)}</td><td>${money(r.trade?.ev)}</td><td>${pct(r.trade?.roi)}</td><td>${r.history?.n_blocks??0}</td></tr>`).join(''):`<tr><td colspan="12">EMPTY — ${state.rows.length?'No matches for this filter.':'Waiting for market observations.'}</td></tr>`;for(const r of $('market-body').querySelectorAll('[data-event]')){r.onclick=()=>select(r.dataset.event);r.onkeydown=e=>{if(e.key==='Enter')select(r.dataset.event);};}}
async function poll(){try{const d=await api('/api/markets');state.rows=d.rows;$('connection').textContent=d.collector.running?'RECORDING':'RECORDER ERROR: '+(d.collector.failure||'stopped');$('cash').textContent='BASIS SIM cash '+money(d.sim.cash);$('feed').textContent=Object.entries(d.sources).filter(([k])=>['catalog','pm','spot','options:BTC','options:ETH','yahoo'].includes(k)).map(([k,v])=>k+' '+v.state).join(' | ')+(d.error?' | MATH ERROR '+d.error:'')+(d.sim.error?' | SIM ERROR '+d.sim.error:'');table();if(state.selected){if(!state.rows.some(r=>r.event_id===state.selected)){$('detail').hidden=true;state.selected=null;}else detail();}}catch(e){$('connection').textContent='SERVICE ERROR — '+e.message;if(!state.rows.length)$('market-body').innerHTML='<tr><td colspan="12">ERROR — '+escape(e.message)+'</td></tr>';}finally{setTimeout(poll,2000);}}
async function select(id){state.selected=id;state.detail=null;$('result').textContent='';$('detail').hidden=false;$('detail-body').textContent='LOADING market math';table();await detail();historyChart();$('detail').scrollIntoView({block:'start'});}
async function detail(){const id=state.selected;try{const d=await api('/api/market?event_id='+encodeURIComponent(id));if(id!==state.selected)return;state.detail=d;renderDetail(d);}catch(e){if(id===state.selected)$('detail-body').textContent='ERROR — '+e.message;}}
function renderDetail(d){const r=d.row,m=r.math,t=r.trade,h=r.history||{};const legs=t?`<table><thead><tr><th>SIDE</th><th>CONTRACT</th><th>BID</th><th>ASK</th><th>ENTRY</th><th>×</th></tr></thead><tbody>${t.legs.map(l=>`<tr><td>${l.side}</td><td>${escape(l.instrument)}</td><td>${money(l.bid)}</td><td>${money(l.ask)}</td><td>${money(l.price)}</td><td>${t.multiplier}</td></tr>`).join('')}</tbody></table>`:'';
 $('detail-body').innerHTML=`<h2>${escape(r.asset)} — ${escape(r.event_text)}</h2><p>${escape(r.event_type)} ${escape(r.direction)} ${n(r.strike_or_threshold)} | cutoff ${time(r.expiry)} | spot ${money(r.spot)}</p><p>PM ${pct(r.pm_yes)} | Q MODEL ${pct(r.opt_yes)} | GAP ${n(m.gap_pp)} pp | REL ${pct(m.relative_gap)} | LOG ODDS ${n(m.log_odds_gap,4)} | ODDS ${n(m.odds_ratio)}×</p><p>PM bid ${pct(r.pm_bid)} / ask ${pct(r.pm_ask)} — ${time(r.pm_timestamp)} — ${escape(r.pm_source)}</p><p>Options ${escape(r.basis_method||'UNAVAILABLE')} | IV ${pct(r.model_inputs?.iv||r.surface_features?.local_iv)} | ${escape(r.model_confidence)} | ${escape(r.source_state)}<br>${escape((r.quality_flags||[]).join(', '))}</p>
 ${t?`<h3>${escape(t.kind.replaceAll('_',' ').toUpperCase())} — ${escape(t.event_exposure)}</h3>${legs}<p>Expiry ${time(t.expiry)} | quoted debit ${money(t.quoted_debit)} | spread vs mid ${money(t.spread_cost)} | slip ${money(t.slippage)} | fees ${money(t.fees)}<br>DEBIT ${money(t.debit)} | MAX PAYOUT ${t.max_payout==null?'uncapped':money(t.max_payout)} | MAX LOSS ${money(t.max_loss)} | ${t.payoff_if_hit!=null?'COST / MAX EXPIRY PAYOUT':'Q EXEC'} ${pct(t.q_exec)}</p><p>PM PAYOFF ${money(t.expected_payoff)} | EV ${money(t.ev)} | ROI ${pct(t.roi)}${t.binary_kelly!=null?' | BINARY-EQUIVALENT KELLY '+pct(t.binary_kelly):''}</p>${t.payoff_if_hit!=null?`<p>Q payoff if hit ${money(t.payoff_if_hit)} / if no hit ${money(t.payoff_if_no_hit)}<br>Q path ${pct(t.q_path)} | Q-only EV ${money(t.baseline_ev)} | PM increment ${money(t.pm_increment)} | Monte Carlo SE ${money(t.mc_standard_error)}<br>Effective paths ${n(t.hit_effective_paths,0)} hit / ${n(t.no_hit_effective_paths,0)} no hit. ${escape(t.payoff_method)}</p>`:`<p>${escape(t.approximation)}</p>`}`:`<p>TRADE NONE — ${escape(r.trade_reason)}</p>`}
 <p>${escape(r.execution_state||'NO_EXECUTION')} | quote receipt age ${n((r.quote_age_ms||0)/1000,1)}s | ${escape(r.chain?.[0]?.quote_quality||'No chain available')}<br>${escape((r.model_limits||[]).join('; '))}</p><h3>MODEL / QUOTE CHECK</h3><p>${(r.candidates||[]).slice(0,3).map(c=>escape(c.kind)+' — '+escape(c.calibration||c.payoff_method)+'; Q payoff '+money(c.q_payoff)+' vs book '+(c.quoted_payoff_band||[]).map(money).join(' / ')+'; PM increment '+money(c.pm_increment)).join('<br>')||'No usable candidate calculations.'}</p><h3>ACTUAL CHAIN</h3><div class="chain-scroll"><table><thead><tr><th>CONTRACT</th><th>K</th><th>C/P</th><th>BID</th><th>ASK</th><th>MARK/LAST</th><th>IV</th><th>VOL</th><th>OI</th></tr></thead><tbody>${(r.chain||[]).map(c=>`<tr><td title="${escape(time(c.source_ms))} source; ${escape(time(c.received_ms))} receipt">${escape(c.instrument)}</td><td>${n(c.strike)}</td><td>${c.option_type==='call'?'C':'P'}</td><td>${money(c.bid)}</td><td>${money(c.ask)}</td><td>${money(c.mark)}</td><td>${pct(c.iv)}</td><td>${n(c.volume,0)}</td><td>${n(c.open_interest,0)}</td></tr>`).join('')||'<tr><td colspan="9">EMPTY — no retained chain covering this cutoff.</td></tr>'}</tbody></table></div><h3>HISTORICAL GAP RESPONSE — EXPLORATORY</h3><p>${escape(h.match||'No comparable history')} | N ${h.n_blocks||0} event/day blocks; ${h.observations||0} openings<br>OPT toward PM @30m ${pct(h.opt_toward_rate)} | PM toward OPT ${pct(h.pm_toward_rate)}<br>Mean OPT move ${n(h.mean_opt_move_pp,4)} pp | mean closure ${n(h.mean_convergence_pp,4)} pp<br>Median half-life ${h.half_life_s==null?'not observed within follow-up':n(h.half_life_s/60,1)+'m'} | ${escape(h.status||'INSUFFICIENT')}</p>
 ${(d.sim.positions||[]).map(p=>`<p>BASIS SIM ${escape(p.structure.kind)} ×${p.quantity} | debit ${money(p.entry_debit)} | liquidation ${money(p.liquidation_value)} | P&L ${money(p.unrealized_pnl)} | ${escape(p.mark_state)} <button data-close="${escape(p.position_id)}">CLOSE STRUCTURE</button></p>`).join('')}`;
 const enabled=t&&['EXECUTABLE_SNAPSHOT','PROXY_EXECUTABLE'].includes(r.execution_state)&&!state.pending;for(const id of ['buy-one','buy-budget','buy-custom'])$(id).disabled=!enabled;$('buy-reason').textContent=state.pending?'ORDER PENDING':enabled?'Exact displayed legs; 1s latency; quotes/cash rechecked at fill.':r.execution_state||r.trade_reason;
 customCost();for(const b of $('detail-body').querySelectorAll('[data-close]'))b.onclick=async()=>{try{const event=state.selected,o=await api('/api/sim/close',{position_id:b.dataset.close});state.pending=o.order_id;$('result').textContent='CLOSE PENDING';track(o.order_id,event);detail();}catch(e){$('result').textContent='REJECTED — '+e.message;}};}
function customCost(){const t=state.detail?.row.trade,q=Number($('quantity').value);if(!t||!Number.isInteger(q)||q<1)return;const turn=t.legs.reduce((a,l)=>a+l.price*t.multiplier,0)*q;const cost=t.quoted_debit*q+turn*(.001+turn/10000*.0005)+turn*.001+.65*t.legs.length*q;$('buy-custom').textContent='PAPER BUY '+q+' / '+money(cost);}
async function buy(p){if(!state.detail?.row.trade||state.pending)return;const event=state.selected;try{const o=await api('/api/sim/buy',{structure_id:state.detail.row.trade.structure_id,...p});state.pending=o.order_id;$('result').textContent='ORDER PENDING — '+o.order_id;renderDetail(state.detail);track(o.order_id,event);}catch(e){$('result').textContent='REJECTED — '+e.message;}}
async function track(id,event){try{const o=await api('/api/sim/order?order_id='+encodeURIComponent(id));if(o.status==='PENDING'){if(o.execution_error&&state.selected===event)$('result').textContent='PENDING / EXECUTION ERROR — '+o.execution_error;setTimeout(()=>track(id,event),500);return;}state.pending=null;if(state.selected===event){showResult(o);detail();}}catch(e){if(state.selected===event)$('result').textContent='STATUS ERROR — '+e.message;setTimeout(()=>track(id,event),2000);}}
function showResult(o){$('result').textContent=o.status==='REJECTED'?'REJECTED — '+o.reason:o.status+' '+(o.instrument||o.side||'')+' ×'+o.quantity+' | '+(o.credit!=null?'credit '+money(o.credit):'debit '+money(o.debit))+' | fees '+money(o.fees)+' | slip '+money(o.slippage)+' | cash '+money(o.cash_after);}
async function historyChart(){const id=state.selected;if(!id)return;const req=++state.request;$('chart-state').textContent='LOADING gap history';try{const d=await api('/api/gap-history?event_id='+encodeURIComponent(id)+'&minutes='+state.minutes);if(req!==state.request||id!==state.selected)return;state.chart=d.rows;$('chart-state').textContent=d.rows.length?state.minutes+'m — PM/OPT above, GAP pp below':'EMPTY — '+d.reason;drawChart();}catch(e){if(req===state.request)$('chart-state').textContent='ERROR — '+e.message;}}
function drawChart(){const a=$('gap-chart'),w=a.clientWidth||600;a.width=w*devicePixelRatio;a.height=180*devicePixelRatio;const c=a.getContext('2d');c.scale(devicePixelRatio,devicePixelRatio);c.clearRect(0,0,w,180);const rows=state.chart;if(!rows.length)return;const left=35,right=w-10,start=rows[0].t,end=rows.at(-1).t,x=t=>left+(right-left)*(t-start)/Math.max(1,end-start),max=Math.max(.1,...rows.map(r=>Math.abs(r.gap||0)));c.strokeStyle='#555';c.beginPath();c.moveTo(left,120);c.lineTo(right,120);c.moveTo(left,150);c.lineTo(right,150);c.stroke();c.font='10px monospace';c.fillStyle='#bbb';c.fillText('100%',0,12);c.fillText('0%',0,112);c.fillText('G pp',0,137);c.fillText('0',12,153);c.fillText(new Date(start).toISOString().slice(11,19),left,178);c.fillText(new Date(end).toISOString().slice(11,19),right-50,178);for(const [field,dash,y] of [['pm',[],v=>110-v*100],['opt',[5,3],v=>110-v*100],['gap',[1,2],v=>150-v/max*24]]){c.strokeStyle='#eee';c.setLineDash(dash);c.beginPath();let prior=null;for(const r of rows){if(r[field]==null){prior=null;continue;}if(prior==null||r.t-prior>15000)c.moveTo(x(r.t),y(r[field]));else c.lineTo(x(r.t),y(r[field]));prior=r.t;}c.stroke();}c.setLineDash([]);}
$('sort').onchange=()=>{state.sort=$('sort').value;table();};$('filter').oninput=()=>{if(state.selected&&!activeRows().some(r=>r.event_id===state.selected)){state.selected=null;state.detail=null;$('detail').hidden=true;}table();};$('refresh').onclick=()=>api('/api/refresh',{requested:true}).catch(e=>$('connection').textContent=e.message);$('hide-detail').onclick=()=>{state.selected=null;$('detail').hidden=true;table();};$('buy-one').onclick=()=>buy({quantity:1});$('buy-budget').onclick=()=>buy({budget:100});$('buy-custom').onclick=()=>buy({quantity:Number($('quantity').value)});$('quantity').oninput=customCost;for(const b of document.querySelectorAll('[data-minutes]'))b.onclick=()=>{state.minutes=Number(b.dataset.minutes);historyChart();};document.addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;if(e.key==='/'){e.preventDefault();$('filter').focus();}else if(e.key.toLowerCase()==='r')$('refresh').click();else if(e.key==='Escape')$('hide-detail').click();else if(['j','k','ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();const rows=activeRows(),at=rows.findIndex(r=>r.event_id===state.selected),i=Math.min(rows.length-1,Math.max(0,at+(['j','ArrowDown'].includes(e.key)?1:-1)));if(rows[i])select(rows[i].event_id);}});window.addEventListener('resize',drawChart);setInterval(()=>{if(state.selected)historyChart();},15000);poll();
