const $=id=>document.getElementById(id);
const state={rows:[],stars:[],selected:null,star:null,detail:null,sort:'created',minutes:30,metric:'return',chart:[],request:0,starSignature:null,holdOrder:null};
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(v,d=2)=>v==null?'--':Math.abs(v)>99999?Number(v).toExponential(2):Number(v).toFixed(d);
const money=v=>v==null?'--':(v<0?'-$':'$')+Math.abs(v).toFixed(2);
const pct=v=>v==null?'--':(v>0&&v<.00005?(v*100).toExponential(2):n(v*100))+'%';
const time=v=>v?new Date(v).toISOString().replace('T',' ').slice(0,19)+' UTC':'--';
const age=v=>v==null?'--':v<60000?n(v/1000,0)+'s':v<3600000?n(v/60000,0)+'m':n(v/3600000,1)+'h';
const legText=t=>(t?.legs||[]).map(l=>l.side+' '+l.instrument).join(' / ');
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||r.statusText);return d;}
function reason(code){if(!code)return '';if(code==='NO_DISPLAYED_STRUCTURE')return 'No option structure was available when starred; no entry opened.';if(code.includes('MISSING_ACTUAL_BID_ASK')||code.includes('MISSING_IMPLIED_VOLATILITY'))return 'Usable option bid/ask and quoted IV are unavailable. Yahoo may still be waiting for delayed opening quotes.';if(code==='NO_CALIBRATED_POSITIVE_PM_INFORMATION')return 'No quote-calibrated structure captures the PM discrepancy.';if(code.startsWith('NO_VALID_POST_TARGET_QUOTE'))return 'No valid exact-contract quote arrived before the recorded entry deadline. '+code.split(':').slice(1).join(':').replaceAll('_',' ');return code.replaceAll('_',' ');}
function activeStar(id){return state.stars.find(s=>s.event_id===id&&['WAITING','LIVE'].includes(s.status));}
function activeRows(){const f=$('filter').value.toLowerCase();const value=r=>state.sort==='gap'?r.math.gap_pp==null?-Infinity:Math.abs(r.math.gap_pp):state.sort==='created'?r.formation?.pm_created_gap_pp:state.sort==='information'?r.trade?.information_drag_ratio:state.sort==='pm'?r.pm_yes:state.sort==='opt'?r.opt_yes:state.sort==='roi'?r.trade?.net_roi:state.sort==='n'?r.history?.n_blocks:r.trade?.net_ev;return state.rows.filter(r=>(r.asset+' '+r.event_text).toLowerCase().includes(f)).sort((a,b)=>(value(b)??-Infinity)-(value(a)??-Infinity)||(b.trade?.information_drag_ratio??-Infinity)-(a.trade?.information_drag_ratio??-Infinity)||Math.abs(b.math.gap_pp||0)-Math.abs(a.math.gap_pp||0)).sort((a,b)=>state.holdOrder?(state.holdOrder.indexOf(a.event_id)<0?Infinity:state.holdOrder.indexOf(a.event_id))-(state.holdOrder.indexOf(b.event_id)<0?Infinity:state.holdOrder.indexOf(b.event_id)):0);}
function table(){const rows=activeRows();$('count').textContent=rows.length+' markets';$('market-body').innerHTML=rows.length?rows.map(r=>{const s=activeStar(r.event_id);return `<tr data-event="${escape(r.event_id)}" tabindex="0" class="${state.selected===r.event_id&&!state.star?'selected':''}"><td><button data-star="${escape(r.event_id)}" aria-label="${s?'Open tracked':'Track'} ${escape(r.asset+' '+r.event_text)}" ${!s&&!r.trade?'disabled':''} title="${escape(!s&&!r.trade?reason(r.trade_reason):'Freeze this signal and exact structure')}">${s?'★ '+s.status:'☆'}</button></td><td>${escape(r.asset)}</td><td title="${escape(r.event_text)}">${escape(r.event_type)} ${n(r.strike_or_threshold,0)} ${r.direction==='up'?'↑':'↓'}</td><td>${time(r.expiry).slice(5,16)}</td><td>${pct(r.pm_yes)}</td><td>${pct(r.opt_yes)}</td><td>${n(r.math.gap_pp)}</td><td>${n(r.math.odds_ratio)}×</td><td title="${escape(r.trade_reason+' / '+r.formation?.provenance)}">${r.trade?escape(r.trade.kind.replaceAll('_',' '))+(r.execution_state==='MARKET_CLOSED'?' [CLOSED]':''):'NONE'}</td><td>${money(r.trade?.debit)}</td><td>${money(r.trade?.net_ev)}</td><td>${pct(r.trade?.net_roi)}</td><td>${r.history?.n_blocks??0}</td></tr>`;}).join(''):`<tr><td colspan="13">EMPTY — ${state.rows.length?'No matches for this filter.':'Waiting for market observations.'}</td></tr>`;
 for(const tr of $('market-body').querySelectorAll('[data-event]')){tr.onclick=()=>selectMarket(tr.dataset.event);tr.onkeydown=e=>{if(e.key==='Enter'&&e.target===tr)selectMarket(tr.dataset.event);};}
 for(const b of $('market-body').querySelectorAll('[data-star]'))b.onclick=e=>{e.stopPropagation();const s=activeStar(b.dataset.star);if(s)selectStar(s.tracking_id);else freeze(rows.find(r=>r.event_id===b.dataset.star));};
 $('star-body').innerHTML=state.stars.length?state.stars.map(s=>`<tr data-tracking="${escape(s.tracking_id)}" tabindex="0" class="${s.tracking_id===state.star?'selected':''}" title="${escape((s.reason||s.quote_state)+' / LAST MARK '+time(s.last_mark))}"><td><button data-remove="${escape(s.tracking_id)}" aria-label="Remove ${escape(s.asset+' '+s.event_text)}" title="Remove from list; preserve history">×</button> ★ ${s.status}</td><td title="${escape(s.event_text)}">${escape(s.asset+' '+s.event_text.slice(0,45))}</td><td>${n(s.star_gap_pp)}</td><td>${n(s.entry_gap_pp)}</td><td title="${escape(legText(s))}">${escape(legText(s)||'NONE')}</td><td>${time(s.target_entry).slice(5,19)}</td><td>${time(s.actual_entry).slice(5,19)}</td><td>${money(s.entry_debit)}</td><td>${money(s.liquidation)}</td><td>${money(s.pnl_1x)}</td><td>${pct(s.return_fraction)}</td><td>${age(s.age_ms)}</td></tr>`).join(''):'<tr><td colspan="12">EMPTY — press ☆ to freeze a signal and its exact suggested structure.</td></tr>';
 for(const tr of $('star-body').querySelectorAll('[data-tracking]')){tr.onclick=()=>selectStar(tr.dataset.tracking);tr.onkeydown=e=>{if(e.key==='Enter'&&e.target===tr)selectStar(tr.dataset.tracking);};}
 for(const b of $('star-body').querySelectorAll('[data-remove]'))b.onclick=e=>{e.stopPropagation();removeStar(b.dataset.remove);};}
async function poll(){try{const d=await api('/api/markets');state.rows=d.rows;state.stars=d.tracking.rows;$('connection').textContent=d.collector.running?'RECORDING':'RECORDER ERROR: '+(d.collector.failure||'stopped');$('feed').textContent=Object.entries(d.sources).filter(([k])=>['catalog','pm','spot','options:BTC','options:ETH','yahoo'].includes(k)).map(([k,v])=>k+' '+v.state).join(' | ')+(d.error?' | MATH ERROR '+d.error:'')+(d.tracking.error?' | TRACKING ERROR '+d.tracking.error:'');table();
 if(state.star){const s=state.stars.find(r=>r.tracking_id===state.star),sig=s&&[s.status,s.last_mark,s.quote_state,s.reason].join(':');if(sig!==state.starSignature)detail();}
 else if(state.selected){if(!state.rows.some(r=>r.event_id===state.selected))closeDetail();else detail();}
 }catch(e){$('connection').textContent='SERVICE ERROR — '+e.message;if(!state.rows.length)$('market-body').innerHTML='<tr><td colspan="13">ERROR — '+escape(e.message)+'</td></tr>';}finally{setTimeout(poll,2000);}}
function closeDetail(){state.selected=null;state.star=null;state.detail=null;$('detail').hidden=true;table();}
async function selectMarket(id){state.selected=id;state.star=null;state.detail=null;state.starSignature=null;$('action-result').textContent='';$('detail').hidden=false;$('detail-body').textContent='LOADING market math';table();await detail();historyChart();$('detail').scrollIntoView({block:'start'});}
async function selectStar(id){state.star=id;state.selected=null;state.detail=null;state.starSignature=null;$('action-result').textContent='';$('detail').hidden=false;$('detail-body').textContent='LOADING frozen signal';table();await detail();$('detail').scrollIntoView({block:'start'});}
async function detail(){const id=state.star||state.selected,isStar=!!state.star;try{const d=await api((isStar?'/api/star?tracking_id=':'/api/market?event_id=')+encodeURIComponent(id));if(id!==(state.star||state.selected)||isStar!==!!state.star)return;state.detail=d;
 if(isStar){const s=d.summary;state.starSignature=[s.status,s.last_mark,s.quote_state,s.reason].join(':');renderDetail(d.frozen.snapshot,d);drawStar(d);}else renderDetail(d.row);
 }catch(e){if(id===(state.star||state.selected))$('detail-body').textContent='ERROR — '+e.message;}}
function renderDetail(r,star=null){const m=r.math,t=r.trade,h=r.history||{},f=r.formation||{},chain=r.chain||(t?.legs||[]);
 const legs=t?`<table><thead><tr><th>SIDE</th><th>EXACT CONTRACT</th><th>BID</th><th>ASK</th><th>ENTRY</th><th>×</th></tr></thead><tbody>${t.legs.map(l=>`<tr><td>${l.side}</td><td>${escape(l.instrument)}</td><td>${money(l.bid)}</td><td>${money(l.ask)}</td><td>${money(l.price)}</td><td>${t.multiplier}</td></tr>`).join('')}</tbody></table>`:'';
 $('detail-body').innerHTML=`<h2>${star?'FROZEN ★ / ':''}${escape(r.asset)} — ${escape(r.event_text)}</h2><p>${escape(r.event_type)} ${escape(r.direction)} ${n(r.strike_or_threshold)} | cutoff ${time(r.expiry)} | spot ${money(r.spot)}<br>PM ${pct(r.pm_yes)} | Q MODEL ${pct(r.opt_yes)} | GAP ${n(m.gap_pp)} pp | REL ${pct(m.relative_gap)} | LOG ODDS ${n(m.log_odds_gap,4)} | ODDS ${n(m.odds_ratio)}×</p><p>${escape(f.provenance||'INSUFFICIENT LOOKBACK')} over prior ${f.window_seconds||30}s | ΔPM ${n(f.delta_pm_pp)} pp | ΔOPT ${n(f.delta_opt_pp)} pp | spot ${pct(f.spot_return)}${f.fresh_pm_unfollowed?' | FRESH PM / OPT NOT FOLLOWED':''}<br>PM bid ${pct(r.pm_bid)} / ask ${pct(r.pm_ask)} — ${time(r.pm_timestamp)}<br>Options ${escape(r.basis_method||'UNAVAILABLE')} | IV ${pct(r.model_inputs?.iv||r.surface_features?.local_iv)} | ${escape(r.model_confidence)} | ${escape(r.source_state)}<br>${escape((r.quality_flags||[]).join(', '))}</p>
 ${t?`<h3>${escape(t.kind.replaceAll('_',' ').toUpperCase())} — EXACT ${star?'STARRED':'SUGGESTED'} STRUCTURE</h3>${legs}<p>Expiry ${time(t.expiry)} | quoted debit ${money(t.quoted_debit)} | entry spread ${money(t.spread_cost)} | slip ${money(t.slippage)} | fees ${money(t.fees)}<br>DEBIT ${money(t.debit)} | MAX LOSS ${money(t.max_loss)} | MAX PAYOUT ${t.max_payout==null?'uncapped':money(t.max_payout)} | DEBIT / MAX ${pct(t.q_exec)} (descriptive)</p><p>PAYOFF IF H ${money(t.payoff_if_hit)} | IF NOT H ${money(t.payoff_if_no_hit)}<br>PM INFORMATION VALUE ${money(t.information_value)} | EXECUTION DRAG ${money(t.execution_drag)} | INFO / DRAG ${n(t.information_drag_ratio)}×<br>PM PAYOFF ${money(t.expected_payoff)} | EXPIRY EV ${money(t.ev)} | NET EV ${money(t.net_ev)} | NET ROI ${pct(t.net_roi)}<br>Estimated exit drag ${money(t.estimated_exit_drag)} | ${escape(t.drag_assumption)}<br>Q event ${pct(t.q_event)} / base path shape ${pct(t.q_path)} | Q-only EV ${money(t.baseline_ev)} | Monte Carlo SE ${money(t.mc_standard_error)} | effective paths ${n(t.hit_effective_paths,0)} / ${n(t.no_hit_effective_paths,0)}<br>${escape(t.calibration)} | ${escape(t.payoff_method)}<br>${escape(r.trade_reason||'')}</p>`:`<p>STRUCTURE NONE — ${escape(r.trade_reason||'No usable suggested payoff')}</p>`}
 ${star?starText(star):`<p>${escape(r.execution_state||'NO_EXECUTION')} | receipt age ${age(r.quote_age_ms)} | ${escape(chain[0]?.quote_quality||'No chain')}<br>${escape((r.model_limits||[]).join('; '))}</p>`}
 <details><summary>${star?'EXACT STARRED CONTRACTS':'ACTUAL CHAIN'} / ${chain.length}</summary><div class="table-scroll"><table><thead><tr><th>CONTRACT</th><th>K</th><th>C/P</th><th>BID</th><th>ASK</th><th>IV</th><th>VOL</th><th>OI</th></tr></thead><tbody>${chain.map(c=>`<tr><td>${escape(c.instrument)}</td><td>${n(c.strike)}</td><td>${c.option_type==='call'?'C':'P'}</td><td>${money(c.bid)}</td><td>${money(c.ask)}</td><td>${pct(c.iv)}</td><td>${n(c.volume,0)}</td><td>${n(c.open_interest,0)}</td></tr>`).join('')}</tbody></table></div></details>
 ${!star?`<details><summary>CANDIDATES / ${(r.candidates||[]).length} — actual quotes, conditional payoffs and friction</summary><div class="table-scroll"><table><thead><tr><th>STRUCTURE / EXACT LEGS</th><th>LEG BID / ASK</th><th>DEBIT</th><th>MAX LOSS</th><th>PAYOFF H</th><th>PAYOFF NOT H</th><th>PM INFO</th><th>DRAG</th><th>INFO/DRAG</th><th>NET EV</th><th>CALIBRATION</th></tr></thead><tbody>${(r.candidates||[]).map(c=>`<tr><td>${escape(c.kind)}<br>${escape(legText(c))}</td><td>${c.legs.map(l=>money(l.bid)+' / '+money(l.ask)).join('<br>')}</td><td>${money(c.debit)}</td><td>${money(c.max_loss)}</td><td>${money(c.payoff_if_hit)}</td><td>${money(c.payoff_if_no_hit)}</td><td>${money(c.information_value)}</td><td>${money(c.execution_drag)}</td><td>${n(c.information_drag_ratio)}×</td><td>${money(c.net_ev)}</td><td>${escape(c.calibration)}</td></tr>`).join('')}</tbody></table></div></details>`:''}
 <p>HISTORICAL / EXPLORATORY — ${escape(h.match||'No comparable history')} | N ${h.n_blocks||0} event/day blocks<br>OPT toward PM @30m ${pct(h.opt_toward_rate)} | PM toward OPT ${pct(h.pm_toward_rate)} | mean target ${n(h.mean_opt_move_pp,4)} pp | closure ${n(h.mean_convergence_pp,4)} pp<br>KM half-life ${h.half_life_s==null?'not observed':n(h.half_life_s/60,1)+'m'} | ${escape(h.status||'INSUFFICIENT')}</p>`;
 const existing=star?star.summary:activeStar(r.event_id);$('track').hidden=false;$('track').disabled=!star&&!existing&&!t;$('stop-track').hidden=!star||!['WAITING','LIVE'].includes(star.summary.status);$('remove-track').hidden=!star;
 $('track').textContent=star?(star.summary.status==='MISSED'?'RETRY / CURRENT SIGNAL':'CURRENT MARKET'):existing?'★ '+existing.status+' / OPEN':'★ TRACK';$('track-state').textContent=existing?'★ '+existing.status+(existing.status==='WAITING'?' — target '+time(existing.target_entry):''):t?'Freeze this signal and these exact legs; first valid quote after ordinary latency.':'Cannot track — '+reason(r.trade_reason);
 $('gap-controls').hidden=!!star;$('return-controls').hidden=!star;
}
function starText(d){const s=d.summary,e=d.entry,m=d.mark,f=d.frozen;return `<h3>★ ${s.status} — ${escape(reason(s.reason)||s.quote_state)}</h3><p>STAR ${time(f.starred_at)} | target entry ${time(f.target_entry)} | deadline ${time(s.entry_deadline)}<br>ACTUAL ENTRY ${time(e?.actual_entry_receipt)} | delay after target ${age(e?.entry_delay_after_target_ms)}<br>STAR GAP ${n(s.star_gap_pp)} pp | ENTRY GAP ${n(s.entry_gap_pp)} pp | capture remaining ${pct(e?.gap_capture_remaining)}<br>ENTRY PM ${pct(e?.pm_entry)} | ENTRY Q ${pct(e?.q_entry)} | spot ${money(e?.spot_entry)}<br>ENTRY DEBIT ${money(e?.debit)} | spread ${money(e?.spread_cost)} | fees ${money(e?.fees)} | slip ${money(e?.slippage)}<br>ENTRY QUOTE ${escape(e?.quote_quality||'--')} | ${escape(e?.source_state||'')}<br>ENTRY INFORMATION ${money(e?.q_entry==null?null:e?.modeled_payoff?.information_value)} | ${escape(e?.model_reason||(e&&e.q_entry==null?'Entry Q was unavailable in the original record.':''))}<br>EXECUTABLE LIQUIDATION ${money(m?.liquidation_credit)} | P&L 1× ${money(m?.pnl_1x)} | RETURN ${pct(m?.return_fraction)} | P&L / $100 ${money(m?.pnl_per_100)}<br>EXIT fees ${money(m?.exit_fees)} | slip ${money(m?.exit_slippage)} | spread ${money(m?.exit_spread)}<br>MID MARK P&L (diagnostic) ${money(m?.mid_mark_pnl)}<br>${escape(s.quote_state)} | LAST MARK ${time(s.last_mark)}${s.ended_at?' | ENDED '+time(s.ended_at):''}<br>Raw STAR ${f.star_raw_boundary} / ENTRY ${e?.raw_id||'--'} / surface ${f.structure?.surface_raw_id||'--'} | ${escape(f.math_version)}</p>`;}
async function freeze(row){if(!row)return;const existing=activeStar(row.event_id);if(existing){selectStar(existing.tracking_id);return;}try{const d=await api('/api/star',{event_id:row.event_id,snapshot_id:row.snapshot_id});state.stars.unshift(d);await selectStar(d.tracking_id);$('action-result').textContent='★ '+d.status+' — original signal and exact structure frozen';table();}catch(e){if($('detail').hidden)await selectMarket(row.event_id);$('action-result').textContent='TRACKING ERROR — '+e.message;}}
async function removeStar(id){try{await api('/api/star/remove',{tracking_id:id});state.stars=state.stars.filter(s=>s.tracking_id!==id);if(state.star===id)closeDetail();table();}catch(e){await selectStar(id);$('action-result').textContent='REMOVE ERROR — '+e.message;}}
async function historyChart(){if(state.star||!state.selected)return;const id=state.selected,req=++state.request;$('chart-state').textContent='LOADING gap history';try{const d=await api('/api/gap-history?event_id='+encodeURIComponent(id)+'&minutes='+state.minutes);if(req!==state.request||id!==state.selected||state.star)return;state.chart=d.rows;$('chart-state').textContent=d.rows.length?state.minutes+'m — PM/OPT above, GAP pp below':'EMPTY — '+d.reason;drawGap();}catch(e){if(req===state.request)$('chart-state').textContent='ERROR — '+e.message;}}
function context(){const a=$('gap-chart'),w=a.clientWidth||600;a.width=w*devicePixelRatio;a.height=190*devicePixelRatio;const c=a.getContext('2d');c.scale(devicePixelRatio,devicePixelRatio);c.clearRect(0,0,w,190);c.font='10px monospace';c.fillStyle='#bbb';c.strokeStyle='#555';return {c,w};}
function drawGap(){const {c,w}=context(),rows=state.chart;if(!rows.length)return;const left=40,right=w-10,start=rows[0].t,end=rows.at(-1).t,x=t=>left+(right-left)*(t-start)/Math.max(1,end-start),max=Math.max(.1,...rows.map(r=>Math.abs(r.gap||0)));c.beginPath();c.moveTo(left,120);c.lineTo(right,120);c.moveTo(left,150);c.lineTo(right,150);c.stroke();c.fillText('100%',0,12);c.fillText('0%',0,112);c.fillText('G pp',0,137);c.fillText('0',12,153);c.fillText(new Date(start).toISOString().slice(11,19),left,186);c.fillText(new Date(end).toISOString().slice(11,19),right-50,186);
 for(const [field,dash,y] of [['pm',[],v=>110-v*100],['opt',[5,3],v=>110-v*100],['gap',[1,2],v=>150-v/max*24]]){c.strokeStyle='#eee';c.setLineDash(dash);c.beginPath();let prior=null;for(const r of rows){if(r[field]==null){prior=null;continue;}if(prior==null||r.t-prior>15000)c.moveTo(x(r.t),y(r[field]));else c.lineTo(x(r.t),y(r[field]));prior=r.t;}c.stroke();}c.setLineDash([]);}
function drawStar(d){const {c,w}=context(),s=d.summary,rows=[...d.series];if(d.end?.final&&(!rows.length||rows.at(-1).timestamp_ms!==d.end.final.timestamp_ms))rows.push(d.end.final);
 const start=d.frozen.starred_at,end=Math.max(start+1000,s.ended_at||Date.now(),rows.at(-1)?.timestamp_ms||0),left=55,right=w-10,x=t=>left+(right-left)*(t-start)/(end-start),value=r=>state.metric==='return'?r.return_fraction*100:r.pnl_1x;
 const values=rows.map(value).filter(v=>v!=null),lo=Math.min(0,...values),hi=Math.max(.1,...values),range=Math.max(.1,hi-lo),y=v=>160-(v-lo)/range*130;
 $('chart-state').textContent=rows.length?(state.metric==='return'?'Executable RETURN %':'Executable 1× P&L $')+' — '+s.quote_state+' / last '+time(s.last_mark)+' / latest '+rows.length+' received marks':s.status==='WAITING'?'★ WAITING — first valid exact-contract quote at/after '+time(s.target_entry):'EMPTY — '+(s.reason||'No executable mark');
 c.beginPath();c.moveTo(left,y(0));c.lineTo(right,y(0));c.stroke();c.fillText(n(hi),0,30);c.fillText(n(lo),0,160);c.fillText(state.metric==='return'?'%':'$',5,90);
 for(const [label,t,dash] of [['STAR',start,[]],[s.actual_entry?'ENTRY':'TARGET',s.actual_entry||s.target_entry,[4,3]]]){if(t>end)continue;c.setLineDash(dash);c.beginPath();c.moveTo(x(t),15);c.lineTo(x(t),165);c.stroke();c.fillText(label,Math.min(right-45,x(t)+4),12);}c.setLineDash([]);c.strokeStyle='#eee';c.beginPath();let prior=null;
 for(const r of rows){const v=value(r);if(v==null)continue;if(prior==null||r.timestamp_ms-prior>180000)c.moveTo(x(r.timestamp_ms),y(v));else c.lineTo(x(r.timestamp_ms),y(v));prior=r.timestamp_ms;}c.stroke();if(rows.length===1){c.beginPath();c.arc(x(rows[0].timestamp_ms),y(value(rows[0])),2,0,Math.PI*2);c.fill();}c.fillText(new Date(start).toISOString().slice(5,16),left,186);c.fillText(new Date(end).toISOString().slice(5,16),right-70,186);}
$('sort').onchange=()=>{state.sort=$('sort').value;table();};$('filter').oninput=()=>{if(!state.star&&state.selected&&!activeRows().some(r=>r.event_id===state.selected))closeDetail();table();};$('refresh').onclick=()=>api('/api/refresh',{requested:true}).catch(e=>$('connection').textContent=e.message);$('hide-detail').onclick=closeDetail;
$('track').onclick=()=>{if(state.star&&state.detail?.frozen)selectMarket(state.detail.frozen.event_id);else if(state.detail?.row)freeze(state.detail.row);};$('remove-track').onclick=()=>{if(state.star)removeStar(state.star);};$('stop-track').onclick=async()=>{if(!state.star)return;try{const stopped=await api('/api/star/stop',{tracking_id:state.star});state.stars=state.stars.map(s=>s.tracking_id===stopped.tracking_id?stopped:s);table();state.starSignature=null;await detail();}catch(e){$('action-result').textContent='TRACKING ERROR — '+e.message;}};
for(const b of document.querySelectorAll('[data-minutes]'))b.onclick=()=>{state.minutes=Number(b.dataset.minutes);historyChart();};for(const b of document.querySelectorAll('[data-metric]'))b.onclick=()=>{state.metric=b.dataset.metric;if(state.star&&state.detail)drawStar(state.detail);};
document.addEventListener('keydown',e=>{if(e.target.matches('input,select'))return;if(e.key==='/'){e.preventDefault();$('filter').focus();}else if(e.key.toLowerCase()==='r')$('refresh').click();else if(e.key==='Escape')closeDetail();else if(e.key.toLowerCase()==='s'&&!state.star&&state.detail?.row)freeze(state.detail.row);else if(['j','k','ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();const rows=activeRows(),at=rows.findIndex(r=>r.event_id===state.selected),i=Math.min(rows.length-1,Math.max(0,at+(['j','ArrowDown'].includes(e.key)?1:-1)));if(rows[i])selectMarket(rows[i].event_id);}});
// Do not move a live-ranked row underneath the operator's pointer.
$('markets').onmouseenter=()=>{state.holdOrder=[...$('market-body').querySelectorAll('[data-event]')].map(r=>r.dataset.event);};$('markets').onmouseleave=()=>{state.holdOrder=null;table();};
window.addEventListener('resize',()=>{if(state.star&&state.detail)drawStar(state.detail);else drawGap();});setInterval(()=>{if(state.selected&&!state.star)historyChart();},15000);poll();
